name: Global Workflow

on:
  workflow_call:
    # inputs:
    #   node-version:
    #     required: true
    #     type: string
    secrets: {}

jobs:
  build:
    strategy:
      matrix:
        node: [18, 19, 20]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Build project
        run: |
          npm install
          npm run build
